<?php

namespace ContainerFQD6fyi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NUNi94bService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nUNi94b' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nUNi94b'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AdminController::listInstructors' => ['privates', '.service_locator.egipcEH.App\\Controller\\AdminController::listInstructors()', 'getAdminControllerlistInstructorsService', true],
            'App\\Controller\\AdminController::promoteInstructor' => ['privates', '.service_locator.WkfvUVe.App\\Controller\\AdminController::promoteInstructor()', 'getAdminControllerpromoteInstructorService', true],
            'App\\Controller\\AdminController::deleteInstructor' => ['privates', '.service_locator.WkfvUVe.App\\Controller\\AdminController::deleteInstructor()', 'getAdminControllerdeleteInstructorService', true],
            'App\\Controller\\AdminController::downgradeAdmin' => ['privates', '.service_locator.WkfvUVe.App\\Controller\\AdminController::downgradeAdmin()', 'getAdminControllerdowngradeAdminService', true],
            'App\\Controller\\AtelierController::index' => ['privates', '.service_locator.10IqLtU.App\\Controller\\AtelierController::index()', 'getAtelierControllerindexService', true],
            'App\\Controller\\AtelierController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\AtelierController::new()', 'getAtelierControllernewService', true],
            'App\\Controller\\AtelierController::show' => ['privates', '.service_locator.CZdTe.W.App\\Controller\\AtelierController::show()', 'getAtelierControllershowService', true],
            'App\\Controller\\AtelierController::edit' => ['privates', '.service_locator.fW1t4FL.App\\Controller\\AtelierController::edit()', 'getAtelierControllereditService', true],
            'App\\Controller\\AtelierController::delete' => ['privates', '.service_locator.fW1t4FL.App\\Controller\\AtelierController::delete()', 'getAtelierControllerdeleteService', true],
            'App\\Controller\\AtelierController::inscription' => ['privates', '.service_locator.fW1t4FL.App\\Controller\\AtelierController::inscription()', 'getAtelierControllerinscriptionService', true],
            'App\\Controller\\AtelierController::desinscription' => ['privates', '.service_locator.fW1t4FL.App\\Controller\\AtelierController::desinscription()', 'getAtelierControllerdesinscriptionService', true],
            'App\\Controller\\AtelierController::noter' => ['privates', '.service_locator.xXb3jrd.App\\Controller\\AtelierController::noter()', 'getAtelierControllernoterService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.5SuUxla.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AdminController:listInstructors' => ['privates', '.service_locator.egipcEH.App\\Controller\\AdminController::listInstructors()', 'getAdminControllerlistInstructorsService', true],
            'App\\Controller\\AdminController:promoteInstructor' => ['privates', '.service_locator.WkfvUVe.App\\Controller\\AdminController::promoteInstructor()', 'getAdminControllerpromoteInstructorService', true],
            'App\\Controller\\AdminController:deleteInstructor' => ['privates', '.service_locator.WkfvUVe.App\\Controller\\AdminController::deleteInstructor()', 'getAdminControllerdeleteInstructorService', true],
            'App\\Controller\\AdminController:downgradeAdmin' => ['privates', '.service_locator.WkfvUVe.App\\Controller\\AdminController::downgradeAdmin()', 'getAdminControllerdowngradeAdminService', true],
            'App\\Controller\\AtelierController:index' => ['privates', '.service_locator.10IqLtU.App\\Controller\\AtelierController::index()', 'getAtelierControllerindexService', true],
            'App\\Controller\\AtelierController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\AtelierController::new()', 'getAtelierControllernewService', true],
            'App\\Controller\\AtelierController:show' => ['privates', '.service_locator.CZdTe.W.App\\Controller\\AtelierController::show()', 'getAtelierControllershowService', true],
            'App\\Controller\\AtelierController:edit' => ['privates', '.service_locator.fW1t4FL.App\\Controller\\AtelierController::edit()', 'getAtelierControllereditService', true],
            'App\\Controller\\AtelierController:delete' => ['privates', '.service_locator.fW1t4FL.App\\Controller\\AtelierController::delete()', 'getAtelierControllerdeleteService', true],
            'App\\Controller\\AtelierController:inscription' => ['privates', '.service_locator.fW1t4FL.App\\Controller\\AtelierController::inscription()', 'getAtelierControllerinscriptionService', true],
            'App\\Controller\\AtelierController:desinscription' => ['privates', '.service_locator.fW1t4FL.App\\Controller\\AtelierController::desinscription()', 'getAtelierControllerdesinscriptionService', true],
            'App\\Controller\\AtelierController:noter' => ['privates', '.service_locator.xXb3jrd.App\\Controller\\AtelierController::noter()', 'getAtelierControllernoterService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.5SuUxla.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AdminController::listInstructors' => '?',
            'App\\Controller\\AdminController::promoteInstructor' => '?',
            'App\\Controller\\AdminController::deleteInstructor' => '?',
            'App\\Controller\\AdminController::downgradeAdmin' => '?',
            'App\\Controller\\AtelierController::index' => '?',
            'App\\Controller\\AtelierController::new' => '?',
            'App\\Controller\\AtelierController::show' => '?',
            'App\\Controller\\AtelierController::edit' => '?',
            'App\\Controller\\AtelierController::delete' => '?',
            'App\\Controller\\AtelierController::inscription' => '?',
            'App\\Controller\\AtelierController::desinscription' => '?',
            'App\\Controller\\AtelierController::noter' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AdminController:listInstructors' => '?',
            'App\\Controller\\AdminController:promoteInstructor' => '?',
            'App\\Controller\\AdminController:deleteInstructor' => '?',
            'App\\Controller\\AdminController:downgradeAdmin' => '?',
            'App\\Controller\\AtelierController:index' => '?',
            'App\\Controller\\AtelierController:new' => '?',
            'App\\Controller\\AtelierController:show' => '?',
            'App\\Controller\\AtelierController:edit' => '?',
            'App\\Controller\\AtelierController:delete' => '?',
            'App\\Controller\\AtelierController:inscription' => '?',
            'App\\Controller\\AtelierController:desinscription' => '?',
            'App\\Controller\\AtelierController:noter' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);
    }
}
