<?php

namespace ContainerFQD6fyi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAtelierControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CZdTe.W.App\Controller\AtelierController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CZdTe.W.App\\Controller\\AtelierController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'atelier' => ['privates', '.errored..service_locator.CZdTe.W.App\\Entity\\Atelier', NULL, 'Cannot autowire service ".service_locator.CZdTe.W": it needs an instance of "App\\Entity\\Atelier" but this type has been excluded in "config/services.yaml".'],
            'noteRepository' => ['privates', 'App\\Repository\\NoteRepository', 'getNoteRepositoryService', true],
        ], [
            'atelier' => 'App\\Entity\\Atelier',
            'noteRepository' => 'App\\Repository\\NoteRepository',
        ]))->withContext('App\\Controller\\AtelierController::show()', $container);
    }
}
