<?php

namespace ContainerFQD6fyi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAtelier2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.fW1t4FL.App\Entity\Atelier' shared service.
     *
     * @return \App\Entity\Atelier
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.fW1t4FL": it needs an instance of "App\\Entity\\Atelier" but this type has been excluded in "config/services.yaml".');
    }
}
