<?php

namespace ContainerFQD6fyi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAtelierControllernoterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xXb3jrd.App\Controller\AtelierController::noter()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xXb3jrd.App\\Controller\\AtelierController::noter()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'atelier' => ['privates', '.errored..service_locator.xXb3jrd.App\\Entity\\Atelier', NULL, 'Cannot autowire service ".service_locator.xXb3jrd": it needs an instance of "App\\Entity\\Atelier" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'noteRepository' => ['privates', 'App\\Repository\\NoteRepository', 'getNoteRepositoryService', true],
        ], [
            'atelier' => 'App\\Entity\\Atelier',
            'entityManager' => '?',
            'noteRepository' => 'App\\Repository\\NoteRepository',
        ]))->withContext('App\\Controller\\AtelierController::noter()', $container);
    }
}
