<?php

namespace ContainerFQD6fyi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAtelierControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fW1t4FL.App\Controller\AtelierController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fW1t4FL.App\\Controller\\AtelierController::delete()'] = ($container->privates['.service_locator.fW1t4FL'] ?? $container->load('get_ServiceLocator_FW1t4FLService'))->withContext('App\\Controller\\AtelierController::delete()', $container);
    }
}
