<?php

namespace ContainerFQD6fyi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAtelierControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.10IqLtU.App\Controller\AtelierController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.10IqLtU.App\\Controller\\AtelierController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'atelierRepository' => ['privates', 'App\\Repository\\AtelierRepository', 'getAtelierRepositoryService', true],
        ], [
            'atelierRepository' => 'App\\Repository\\AtelierRepository',
        ]))->withContext('App\\Controller\\AtelierController::index()', $container);
    }
}
